# Store non-sensitive configuration settings here.  Acessible from Rails.configuration.settings
defaults: &defaults
  cas_base: 'https://login-test.cc.nd.edu/cas'
  background_processing: true
  export_batch_size: 750

local: &local
  <<: *defaults
  image_server_url: 'http://localhost:3019'
  beehive_url: 'http://localhost:3018'
  media_server_url: 'http://localhost:3023'
  aws:
    region: us-east-1
    bucket: testlibnd-wse-honeycomb-dev
    profile: honeycomb

vm: &vm
  <<: *defaults

development:
  <<: *local
  background_processing: false

test:
  <<: *local
  background_processing: false

pre_production:
  <<: *vm
  cas_base: https://login.nd.edu/cas
  image_server_url: https://honeypotpprd.library.nd.edu
  beehive_url: https://collections-pprd.library.nd.edu
  media_server_url: https://buzz-pprd.library.nd.edu
  aws:
    region: us-east-1
    bucket: testlibnd-wse-honeycomb-pprd
    profile: honeycomb

production:
  <<: *vm
  cas_base: https://login.nd.edu/cas
  image_server_url: https://honeypot.library.nd.edu
  beehive_url: https://collections.library.nd.edu
  media_server_url: https://buzz.library.nd.edu
  aws:
    region: us-east-1
    bucket: honeycomb-media-wse-library-nd-edu
    profile: a_wse_honeycomb
