default: &default
  hostname: localhost
  port: 8983
  path: /solr/default
development:
  <<: *default
  path: /solr/honeycomb
test:
  <<: *default
  port: 8981
  path: /solr/test
pre_production:
  <<: *default
  port: 8080
  path: /solr/honeycomb
prep:
  <<: *default
  port: 8080
  path: /solr/honeycomb
production:
  <<: *default
  port: 8080
  path: /solr/honeycomb
