name: Rspec Tests CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      RAILS_ENV: test
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Node modules
      run: npm install
    - name: Set up Ruby
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Bundler install
      run: bundle install --jobs 4 --retry 3
    - name: Setup database
      run: |
        cp config/secrets.example.yml config/secrets.yml
        cp config/database_example.yml config/database.yml
        psql -c 'create database honeycomb_test' -U postgres
        psql -c 'create role root superuser createdb createrole inherit login replication' -U postgres
        bundle exec rake --trace db:migrate test
    - name: Setup Code Climate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Run tests
      run: bundle exec rspec spec
      env:
        COVERAGE: true
    - name: Publish code coverage
      env:
        CC_TEST_REPORTER_ID: d27c5b84a9b2ca09b11fbed190cdd93fcbe2a5a21fd19283a5ebebad4e2552be
      run: |
        export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
        ./cc-test-reporter after-build -r ${CC_TEST_REPORTER_ID}
