name: Rspec Tests CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Node modules
      run: npm install
    - name: Set up Ruby
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Setup database
      run: |
        cp config/secrets.example.yml config/secrets.yml
        cp config/database_example.yml config/database.yml
        psql -c 'create database honeycomb_test' -U postgres
        psql -c 'create role root superuser createdb createrole inherit login replication' -U postgres
        RAILS_ENV=test bundle exec rake --trace db:migrate test
    - name: Run Tests and publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: d27c5b84a9b2ca09b11fbed190cdd93fcbe2a5a21fd19283a5ebebad4e2552be
      with:
        coverageCommand: bundle exec rspec spec
